// PATH: src/app_teacher/domains/fees/api.ts
// 수납(Fees) API facade. Canonical contract lives in shared.
export {
  // types
  type FeeType,
  type BillingCycle,
  type InvoiceStatus,
  type PaymentMethod,
  type FeeTemplate,
  type StudentFee,
  type InvoiceItem,
  type FeePayment,
  type StudentInvoice,
  type FeeTypeStat,
  type DashboardStats,
  type LectureOption,
  // API calls
  fetchLectureOptions,
  fetchFeeTemplates,
  createFeeTemplate,
  updateFeeTemplate,
  deleteFeeTemplate,
  fetchStudentFees,
  createStudentFee,
  bulkAssignStudentFees,
  deleteStudentFee,
  fetchInvoices,
  fetchInvoiceDetail,
  generateInvoices,
  cancelInvoice,
  fetchPayments,
  recordPayment,
  cancelPayment,
  fetchDashboard,
  fetchOverdueInvoices,
} from "@/shared/api/contracts/fees";
